kind: pipeline
type: docker
name: demo-ci

steps:
#  - name: test
#    image: adoptopenjdk/openjdk15:jdk-15.0.1_9-slim
#    commands:
#      - echo "skip automatic test"
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: ci
      username: drone
      icon_emoji: ":drone:"
    when:
      status: [ success, failure ]