version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql
    hostname: container_mysql_hostname
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    command:
      - --max_allowed_packet=104857600
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d

